foreground #c0caf5
background #1a1b26
selection_foreground #1a1b26
selection_background #7aa2f7
url_color #73daca

scrollback_line 0

cursor #c0caf5
cursor_text_color #1a1b26

# black
color0 #15161e
color8 #414868

# red
color1 #f7768e
color9 #ff899d

# green
color2 #9ece6a
color10 #b9f27c

# yellow
color3 #e0af68
color11 #ffcf8b

# blue
color4 #7aa2f7
color12 #9ab8ff

# magenta
color5 #bb9af7
color13 #d5b0ff

# cyan
color6 #7dcfff
color14 #a4daff

# white
color7 #a9b1d6
color15 #c0caf5
